#!/bin/bash
# ==============================================================================
# userdata.sh — OpenClaw First-Boot Script (OCI)
# ==============================================================================
#
# Rendered by templatefile() in compute.tf, which evaluates every Terraform
# interpolation and for-directive BEFORE this file ever reaches bash. A shell
# variable must therefore be written with a DOUBLED dollar sign so it survives
# that pass and is expanded here at run time.
#
# CAREFUL: templatefile parses the ENTIRE file, COMMENTS INCLUDED. An
# unescaped interpolation written in a comment -- even purely as an example --
# fails the apply with:
#
#     Call to function "templatefile" failed: ./scripts/userdata.sh:6,69-72:
#     Invalid expression; Expected the start of an expression, but found an
#     invalid expression token.
#
# and the line/column it names is inside the comment, which reads like
# nonsense until you know this. Describe the syntax in words here; never write
# a literal example of it.
#
# Runs once at first boot on the openclaw-image instance:
#   1. Set the openclaw Linux user password.
#   2. Write the LiteLLM OCI credentials to /etc/litellm.env and the signing
#      key to /etc/litellm-key.pem.
#   3. Write /opt/openclaw/litellm-config.yaml — one entry per configured model.
#   4. Register those same models with OpenClaw and set the primary.
#   5. Start litellm and openclaw-gateway.
#   6. Refresh the APT package lists baked into the image.
#
# Steps 3 and 4 are both generated from var.models, so the LiteLLM routing table
# and the OpenClaw model picker cannot disagree about what exists.
#
# ==============================================================================

set -euo pipefail

LOG=/root/userdata.log
mkdir -p /root
touch "$LOG"
chmod 600 "$LOG"
exec > >(tee -a "$LOG" | logger -t user-data -s 2>/dev/console) 2>&1
trap 'echo "ERROR at line $LINENO"; exit 1' ERR

echo "NOTE: user-data start: $(date -Is)"

systemctl stop xrdp

# ==============================================================================
# Host Firewall
# ==============================================================================
#
# OCI's Ubuntu images ship an iptables INPUT chain that permits only SSH.
# Everything else is DROPPED AT THE HOST, regardless of what the NSG and the
# subnet security list allow — and OCI evaluates all three.
#
# This is the single most confusing failure in the whole deploy, because
# nothing reports an error: the instance is RUNNING, cloud-init succeeds, xrdp
# is active, the NSG shows 3389 open, and the RDP client just times out with
# "nothing listening". `ss -tlnp` on the box shows xrdp bound to 0.0.0.0:3389
# the entire time.
#
# AWS has no host firewall on its Ubuntu AMI, which is why aws-openclaw needs
# nothing here and this does. It is the first thing every other OCI project in
# this repo does at boot.
#
# TODO: restrict the source CIDR and open only 3389 for production. Wide open
# matches the lab posture of the security list in 01-core.
#
# ==============================================================================

echo "NOTE: [firewall] opening the OCI host firewall"
iptables -I INPUT -s 0.0.0.0/0 -j ACCEPT
echo "NOTE: [firewall] done"


# ==============================================================================
# Credentials
# ==============================================================================
#
# The password is generated by Terraform and injected directly.
#
# ==============================================================================

echo "NOTE: [credentials] setting openclaw user password"
echo "openclaw:${openclaw_password}" | chpasswd
echo "NOTE: [credentials] done"


# ==============================================================================
# LiteLLM OCI Credentials
# ==============================================================================
#
# THIS IS THE ONE PLACE ON THE BOX THAT HOLDS A KEY.
#
# LiteLLM's oci/ provider can authenticate with an instance principal, but only
# when handed a live oci.signer object through the Python SDK. The proxy is
# configured from YAML and environment variables, and those paths resolve
# manual credentials only. So the Gen AI call — and nothing else — uses the
# dedicated openclaw-svc user created in 01-core, whose only grant is
# "use generative-ai-family".
#
# Everything else the desktop does, including every OCI CLI command the agent
# runs, goes through the instance principal and needs no key at all.
#
# Both files are 0600 and owned by openclaw, the user litellm.service runs as.
#
# ==============================================================================

echo "NOTE: [litellm] writing OCI signing key"
install -m 600 -o openclaw -g openclaw /dev/null /etc/litellm-key.pem
cat > /etc/litellm-key.pem <<'PEMKEY'
${litellm_private_key}
PEMKEY
chmod 600 /etc/litellm-key.pem
chown openclaw:openclaw /etc/litellm-key.pem

echo "NOTE: [litellm] writing OCI credential environment file"
cat > /etc/litellm.env <<ENVFILE
OCI_REGION=${region}
OCI_TENANCY=${tenancy_ocid}
OCI_USER=${litellm_user_ocid}
OCI_FINGERPRINT=${litellm_fingerprint}
OCI_KEY_FILE=/etc/litellm-key.pem
OCI_COMPARTMENT_ID=${compartment_ocid}
ENVFILE
chmod 600 /etc/litellm.env
chown openclaw:openclaw /etc/litellm.env

# The shipped litellm.service knows nothing about OCI. Rather than bake
# credentials into the unit at image-build time — where they would end up in
# the custom image, readable by anyone who can launch from it — the env file is
# attached here with a drop-in.
echo "NOTE: [litellm] attaching credentials to litellm.service"
mkdir -p /etc/systemd/system/litellm.service.d
cat > /etc/systemd/system/litellm.service.d/oci.conf <<'DROPIN'
[Service]
EnvironmentFile=/etc/litellm.env
DROPIN
systemctl daemon-reload
echo "NOTE: [litellm] credentials wired"


# ==============================================================================
# LiteLLM Config
# ==============================================================================
#
# One model_list entry per model in genai-config.sh, generated by the
# for-directive below. Any number from 1 upward renders correctly.
#
# The credentials are read from the environment file above — LiteLLM resolves
# OCI_USER, OCI_FINGERPRINT, OCI_TENANCY, OCI_KEY_FILE, OCI_COMPARTMENT_ID and
# OCI_REGION on its own, but they are named explicitly per model so the wiring
# is visible rather than implied.
#
# drop_params is on because OpenClaw sends OpenAI parameters that several OCI
# models do not accept; without it a request carrying an unsupported field is
# rejected outright instead of being trimmed.
#
# ==============================================================================

echo "NOTE: [litellm] writing config"
cat > /opt/openclaw/litellm-config.yaml <<LITELLM
model_list:
%{ for m in models ~}
  - model_name: ${m.alias}
    litellm_params:
      model: oci/${m.model}
      oci_region: os.environ/OCI_REGION
      oci_user: os.environ/OCI_USER
      oci_fingerprint: os.environ/OCI_FINGERPRINT
      oci_tenancy: os.environ/OCI_TENANCY
      oci_key_file: os.environ/OCI_KEY_FILE
      oci_compartment_id: os.environ/OCI_COMPARTMENT_ID
%{ if m.native_streaming == false ~}
    model_info:
      supports_native_streaming: false
%{ endif ~}

%{ endfor ~}
litellm_settings:
  drop_params: true

general_settings:
  master_key: "sk-openclaw"
  drop_params: true
LITELLM
chown openclaw:openclaw /opt/openclaw/litellm-config.yaml
echo "NOTE: [litellm] config written for these models:"
grep '^  - model_name:' /opt/openclaw/litellm-config.yaml


# ==============================================================================
# Register the models with OpenClaw
# ==============================================================================
#
# This runs at BOOT rather than at image-build time, because the model list is
# a deploy-time decision. 02-packer/scripts/09-openclaw-init.sh only stamps the
# config with internal metadata (without which OpenClaw discards a pre-written
# config on first launch); the actual model set is written here.
#
# The provider blob arrives base64-encoded. Raw JSON interpolated into a shell
# script breaks the moment a display name contains an apostrophe; base64 is
# alphanumeric plus +/= so there is no quoting case at all.
#
# Failures are logged loudly but do not abort the boot. A box that comes up
# with the wrong model picker is still reachable over RDP and can be fixed in
# place; one that aborts cloud-init has no password set and cannot be logged
# into at all.
#
# ==============================================================================

OPENCLAW_BIN=/usr/local/bin/openclaw
MODELS_JSON=$(echo '${models_b64}' | base64 -d)
PRIMARY_ALIAS='${primary_alias}'

# {baseUrl, apiKey, models:[{id,name},...]} — assembled with jq so the models
# array is spliced in as structured data rather than pasted as text.
PROVIDER_JSON=$(jq -n --argjson models "$${MODELS_JSON}" '{
  baseUrl: "http://localhost:4000",
  apiKey:  "sk-openclaw",
  models:  $models
}')

run_openclaw() {
  sudo -u openclaw env HOME=/home/openclaw PATH=/usr/local/bin:/usr/bin:/bin \
    "$${OPENCLAW_BIN}" "$@"
}

echo "NOTE: [models] registering the litellm provider with OpenClaw"
if ! run_openclaw config set models.providers.litellm "$${PROVIDER_JSON}" --strict-json; then
  echo "ERROR: [models] failed to register the litellm provider — the model"
  echo "ERROR: [models] picker will show whatever the image was built with."
fi

# Register each model. `openclaw models set` also repoints the default as a
# side effect — it logs "Default model: ..." — so the primary is set right
# afterwards to land on the intended one.
#
# DO NOT remove this loop. It was removed once on the reasoning that the
# provider config above already declares the models and this only sets a
# default. That reasoning was never tested, and the next build came up with an
# empty model picker. aws-openclaw does the same thing; keep it.
echo "$${MODELS_JSON}" | jq -r '.[].id' | while read -r alias; do
  if run_openclaw models set "litellm/$${alias}"; then
    echo "NOTE: [models] registered litellm/$${alias}"
  else
    echo "ERROR: [models] could not register litellm/$${alias}"
  fi
done

echo "NOTE: [models] setting primary to litellm/$${PRIMARY_ALIAS}"
if ! run_openclaw config set agents.defaults.model.primary "litellm/$${PRIMARY_ALIAS}"; then
  echo "ERROR: [models] failed to set the primary model — agents will fall back"
  echo "ERROR: [models] to whatever the image had, which may not do tool calls."
fi

run_openclaw approvals allowlist add --agent '*' '/**'    || true
run_openclaw approvals allowlist add --agent 'main' '/**' || true

chown -R openclaw:openclaw /home/openclaw/.openclaw
echo "NOTE: [models] done"


# ==============================================================================
# Start Services
# ==============================================================================

# RESTART, NOT START. Both units are enabled at image-build time, so systemd
# brings them up during boot — with the placeholder config baked into the
# image — well before cloud-init gets here and rewrites that config. By this
# point they are already running, and `systemctl start` on a running service
# is a silent no-op: it returns 0, logs nothing, and leaves the old config
# loaded.
#
# The symptom is that the model picker offers a model LiteLLM has never heard
# of, and OpenClaw reports "The selected model was not found by the provider"
# while /root/userdata.log shows every step succeeding.
#
# aws-openclaw has the same race and never trips it, because its build-time
# placeholder lists the same four Bedrock models the runtime config does — so
# a stale proxy happens to serve the right names anyway.

echo "NOTE: [services] restarting litellm to load the generated config"
systemctl restart litellm

echo "NOTE: [services] restarting openclaw-gateway"
systemctl stop openclaw-gateway

echo "NOTE: [services] done"


# ==============================================================================
# Refresh APT Package Lists
# ==============================================================================
#
# The image bakes /var/lib/apt/lists from whenever Packer ran, and
# 01-packages.sh deliberately disables apt-daily so nothing ever refreshes it.
# Ubuntu rotates point versions constantly, so within days an `apt install` on
# a deployed instance fails with dependencies "not installable" — the package
# is real, the baked index just does not know its current version:
#
#     apache2-bin : Depends: libaprutil1t64 (>= 1.6.0) but it is not installable
#
# That reads like a broken image rather than a stale index, which is why it is
# refreshed here. The timers stay disabled on purpose — unattended-upgrades
# restarting things mid-demo is worse than a slightly old index.
#
# Deliberately last, and deliberately non-fatal: it runs after the password is
# set and the services are up, so a transient mirror failure cannot leave an
# instance nobody can log into.
#
# ==============================================================================

echo "NOTE: [apt] refreshing package lists"
if apt-get update -y > /dev/null 2>&1; then
  echo "NOTE: [apt] package lists refreshed"
else
  echo "WARN: [apt] refresh failed — run 'sudo apt-get update' before installing"
fi


# ==============================================================================
# Persist the Firewall Rule
# ==============================================================================
#
# The iptables rule added at the top of this script lives in memory only.
# Without this the instance comes up fine, works all day, and then silently
# stops accepting RDP after the first reboot — with cloud-init not re-running
# to fix it, because user_data executes once.
#
# Saved last rather than immediately, so the rule that gets persisted is the
# one a fully-booted, working instance was actually using.
#
# ==============================================================================

echo "NOTE: [firewall] persisting iptables rules across reboots"
netfilter-persistent save
echo "NOTE: [firewall] persisted"

systemctl start openclaw-gateway
systemctl start xrdp

curl -s localhost:4000/v1/models -H "Authorization: Bearer sk-openclaw" | jq -r '.data[].id'

echo "NOTE: user-data complete: $(date -Is)"

