#!/bin/bash
# ================================================================================
# userdata.sh — OpenClaw First-Boot Script (OCI)
# ================================================================================
#
# Rendered by templatefile() in compute.tf, which evaluates every Terraform
# interpolation and for-directive BEFORE this file ever reaches bash. A shell
# variable must therefore be written with a DOUBLED dollar sign so it survives
# that pass and is expanded here at run time.
#
# CAREFUL: templatefile parses the ENTIRE file, COMMENTS INCLUDED. An
# unescaped interpolation written in a comment -- even purely as an example --
# fails the apply with:
#
#     Call to function "templatefile" failed: ./scripts/userdata.sh:6,69-72:
#     Invalid expression; Expected the start of an expression, but found an
#     invalid expression token.
#
# and the line/column it names is inside the comment, which reads like
# nonsense until you know this. Describe the syntax in words here; never write
# a literal example of it.
#
# Runs once at first boot on the openclaw-image instance:
#   1. Set the openclaw Linux user password.
#   2. Write the LiteLLM OCI credentials to /etc/litellm.env and the signing
#      key to /etc/litellm-key.pem.
#   3. Write /opt/openclaw/litellm-config.yaml — one entry per configured model.
#   4. Register those same models with OpenClaw and set the primary.
#   5. Configure msmtp for OCI Email Delivery (skipped when email is disabled).
#   6. Start litellm and openclaw-gateway.
#
# Steps 3 and 4 are both generated from var.models, so the LiteLLM routing table
# and the OpenClaw model picker cannot disagree about what exists.
#
# ================================================================================

set -euo pipefail

LOG=/root/userdata.log
mkdir -p /root
touch "$LOG"
chmod 600 "$LOG"
exec > >(tee -a "$LOG" | logger -t user-data -s 2>/dev/console) 2>&1
trap 'echo "ERROR at line $LINENO"; exit 1' ERR

echo "NOTE: user-data start: $(date -Is)"


# ================================================================================
# Credentials
# ================================================================================
#
# No secret store call here, unlike the AWS build. OCI Vault is unusable in an
# apply/destroy loop — a deleted vault sits in PENDING_DELETION for 30 days
# while still consuming a default tenancy limit of one — so the password is
# generated by Terraform and injected directly. See 03-openclaw/accounts.tf.
#
# ================================================================================

echo "NOTE: [credentials] setting openclaw user password"
echo "openclaw:${openclaw_password}" | chpasswd
echo "NOTE: [credentials] done"


# ================================================================================
# LiteLLM OCI Credentials
# ================================================================================
#
# THIS IS THE ONE PLACE ON THE BOX THAT HOLDS A KEY.
#
# LiteLLM's oci/ provider can authenticate with an instance principal, but only
# when handed a live oci.signer object through the Python SDK. The proxy is
# configured from YAML and environment variables, and those paths resolve
# manual credentials only. So the Gen AI call — and nothing else — uses the
# dedicated openclaw-svc user created in 01-core, whose only grant is
# "use generative-ai-family".
#
# Everything else the desktop does, including every OCI CLI command the agent
# runs, goes through the instance principal and needs no key at all.
#
# Both files are 0600 and owned by openclaw, the user litellm.service runs as.
#
# ================================================================================

echo "NOTE: [litellm] writing OCI signing key"
install -m 600 -o openclaw -g openclaw /dev/null /etc/litellm-key.pem
cat > /etc/litellm-key.pem <<'PEMKEY'
${litellm_private_key}
PEMKEY
chmod 600 /etc/litellm-key.pem
chown openclaw:openclaw /etc/litellm-key.pem

echo "NOTE: [litellm] writing OCI credential environment file"
cat > /etc/litellm.env <<ENVFILE
OCI_REGION=${region}
OCI_TENANCY=${tenancy_ocid}
OCI_USER=${litellm_user_ocid}
OCI_FINGERPRINT=${litellm_fingerprint}
OCI_KEY_FILE=/etc/litellm-key.pem
OCI_COMPARTMENT_ID=${compartment_ocid}
ENVFILE
chmod 600 /etc/litellm.env
chown openclaw:openclaw /etc/litellm.env

# The shipped litellm.service knows nothing about OCI. Rather than bake
# credentials into the unit at image-build time — where they would end up in
# the custom image, readable by anyone who can launch from it — the env file is
# attached here with a drop-in.
echo "NOTE: [litellm] attaching credentials to litellm.service"
mkdir -p /etc/systemd/system/litellm.service.d
cat > /etc/systemd/system/litellm.service.d/oci.conf <<'DROPIN'
[Service]
EnvironmentFile=/etc/litellm.env
DROPIN
systemctl daemon-reload
echo "NOTE: [litellm] credentials wired"


# ================================================================================
# LiteLLM Config
# ================================================================================
#
# One model_list entry per model in genai-config.sh, generated by the
# for-directive below. Any number from 1 upward renders correctly.
#
# The credentials are read from the environment file above — LiteLLM resolves
# OCI_USER, OCI_FINGERPRINT, OCI_TENANCY, OCI_KEY_FILE, OCI_COMPARTMENT_ID and
# OCI_REGION on its own, but they are named explicitly per model so the wiring
# is visible rather than implied.
#
# drop_params is on because OpenClaw sends OpenAI parameters that several OCI
# models do not accept; without it a request carrying an unsupported field is
# rejected outright instead of being trimmed.
#
# ================================================================================

echo "NOTE: [litellm] writing config"
cat > /opt/openclaw/litellm-config.yaml <<LITELLM
model_list:
%{ for m in models ~}
  - model_name: ${m.alias}
    litellm_params:
      model: oci/${m.model}
      oci_region: os.environ/OCI_REGION
      oci_user: os.environ/OCI_USER
      oci_fingerprint: os.environ/OCI_FINGERPRINT
      oci_tenancy: os.environ/OCI_TENANCY
      oci_key_file: os.environ/OCI_KEY_FILE
      oci_compartment_id: os.environ/OCI_COMPARTMENT_ID

%{ endfor ~}
litellm_settings:
  drop_params: true

general_settings:
  master_key: "sk-openclaw"
  drop_params: true
LITELLM
chown openclaw:openclaw /opt/openclaw/litellm-config.yaml
echo "NOTE: [litellm] config written for these models:"
grep '^  - model_name:' /opt/openclaw/litellm-config.yaml


# ================================================================================
# Register the models with OpenClaw
# ================================================================================
#
# This runs at BOOT rather than at image-build time, because the model list is
# a deploy-time decision. 02-packer/scripts/09-openclaw-init.sh only stamps the
# config with internal metadata (without which OpenClaw discards a pre-written
# config on first launch); the actual model set is written here.
#
# The provider blob arrives base64-encoded. Raw JSON interpolated into a shell
# script breaks the moment a display name contains an apostrophe; base64 is
# alphanumeric plus +/= so there is no quoting case at all.
#
# Failures are logged loudly but do not abort the boot. A box that comes up
# with the wrong model picker is still reachable over RDP and can be fixed in
# place; one that aborts cloud-init has no password set and cannot be logged
# into at all.
#
# ================================================================================

OPENCLAW_BIN=/usr/local/bin/openclaw
MODELS_JSON=$(echo '${models_b64}' | base64 -d)
PRIMARY_ALIAS='${primary_alias}'

# {baseUrl, apiKey, models:[{id,name},...]} — assembled with jq so the models
# array is spliced in as structured data rather than pasted as text.
PROVIDER_JSON=$(jq -n --argjson models "$${MODELS_JSON}" '{
  baseUrl: "http://localhost:4000",
  apiKey:  "sk-openclaw",
  models:  $models
}')

run_openclaw() {
  sudo -u openclaw env HOME=/home/openclaw PATH=/usr/local/bin:/usr/bin:/bin \
    "$${OPENCLAW_BIN}" "$@"
}

echo "NOTE: [models] registering the litellm provider with OpenClaw"
if ! run_openclaw config set models.providers.litellm "$${PROVIDER_JSON}" --strict-json; then
  echo "ERROR: [models] failed to register the litellm provider — the model"
  echo "ERROR: [models] picker will show whatever the image was built with."
fi

# Register each alias, then set the primary last so it ends up selected.
echo "$${MODELS_JSON}" | jq -r '.[].id' | while read -r alias; do
  if run_openclaw models set "litellm/$${alias}"; then
    echo "NOTE: [models] registered litellm/$${alias}"
  else
    echo "ERROR: [models] could not register litellm/$${alias}"
  fi
done

echo "NOTE: [models] setting primary to litellm/$${PRIMARY_ALIAS}"
if ! run_openclaw config set agents.defaults.model.primary "litellm/$${PRIMARY_ALIAS}"; then
  echo "ERROR: [models] failed to set the primary model — agents will fall back"
  echo "ERROR: [models] to whatever the image had, which may not do tool calls."
fi

run_openclaw approvals allowlist add --agent '*' '/**'    || true
run_openclaw approvals allowlist add --agent 'main' '/**' || true

chown -R openclaw:openclaw /home/openclaw/.openclaw
echo "NOTE: [models] done"


# ================================================================================
# Email (OCI Email Delivery — optional)
# ================================================================================
#
# smtp_host is empty when var.email_sender was left unset in 01-core, in which
# case the whole block is skipped and the desktop simply has no mail.
#
# Note the asymmetry with AWS: the instance principal is NOT granted Email
# Delivery API permissions, so the agent cannot send through the OCI CLI. msmtp
# with these SMTP credentials is the only path, which is why SYSTEM.md says so
# explicitly — an agent that discovers `oci email` will otherwise keep trying it.
#
# ================================================================================

SMTP_HOST="${smtp_host}"
SMTP_USERNAME="${smtp_username}"
SMTP_PASSWORD="${smtp_password}"
SMTP_FROM="${smtp_from}"

if [ -n "$${SMTP_HOST}" ]; then
  echo "NOTE: [email] injecting SMTP credentials into gateway service"
  mkdir -p /etc/systemd/system/openclaw-gateway.service.d
  cat > /etc/systemd/system/openclaw-gateway.service.d/smtp.conf <<EOF
[Service]
Environment="SMTP_HOST=$${SMTP_HOST}"
Environment="SMTP_PORT=587"
Environment="SMTP_USERNAME=$${SMTP_USERNAME}"
Environment="SMTP_PASSWORD=$${SMTP_PASSWORD}"
Environment="SMTP_FROM=$${SMTP_FROM}"
EOF
  systemctl daemon-reload

  echo "NOTE: [email] configuring msmtp for system-wide email sending"
  cat > /etc/msmtprc <<EOF
defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log

account        oci
host           $${SMTP_HOST}
port           587
from           $${SMTP_FROM}
user           $${SMTP_USERNAME}
password       $${SMTP_PASSWORD}

account default : oci
EOF
  chmod 600 /etc/msmtprc
  touch /var/log/msmtp.log
  chmod 666 /var/log/msmtp.log

  cp /etc/msmtprc /home/openclaw/.msmtprc
  chown openclaw:openclaw /home/openclaw/.msmtprc
  chmod 600 /home/openclaw/.msmtprc

  echo "NOTE: [email] writing email capability note to agent workspace"
  mkdir -p /home/openclaw/.openclaw/agents/main/workspace
  cat > /home/openclaw/.openclaw/agents/main/workspace/EMAIL.md <<EOF
# Email Sending

msmtp is configured system-wide with OCI Email Delivery SMTP credentials.
Use the \`mail\` command via exec to send email — no additional setup needed.

The instance principal does NOT have Email Delivery API permissions, so
\`oci email\` commands will fail. Always use \`mail\`.

## Send a plain text email
\`\`\`bash
echo "Message body here" | mail -s "Subject" recipient@example.com
\`\`\`

## Send with a file attachment
\`\`\`bash
mail -s "Subject" -A /path/to/file.docx recipient@example.com < /dev/null
\`\`\`

## Send with body and attachment
\`\`\`bash
echo "Please find the report attached." | mail -s "Report" -A /path/to/report.docx recipient@example.com
\`\`\`

From address: $${SMTP_FROM}
EOF
  chown -R openclaw:openclaw /home/openclaw/.openclaw/agents/main/workspace

  echo "NOTE: [email] done"
else
  echo "NOTE: [email] no sender configured, skipping"
fi


# ================================================================================
# Start Services
# ================================================================================

echo "NOTE: [services] starting litellm"
systemctl start litellm

echo "NOTE: [services] starting openclaw-gateway"
systemctl start openclaw-gateway

echo "NOTE: [services] done"

echo "NOTE: user-data complete: $(date -Is)"
