#!/bin/bash
# ==============================================================================
# get_password.sh
# ------------------------------------------------------------------------------
# Prints the openclaw desktop password.
#
# The password is generated by Terraform; this reads it back out of state.
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${SCRIPT_DIR}/03-openclaw"

if [ ! -f terraform.tfstate ]; then
  echo "ERROR: No Terraform state in 03-openclaw — run ./apply.sh first." >&2
  exit 1
fi

USERNAME=$(terraform output -raw openclaw_username 2>/dev/null || echo "openclaw")
PASSWORD=$(terraform output -raw openclaw_password 2>/dev/null || echo "")

if [ -z "${PASSWORD}" ]; then
  echo "ERROR: Password not found in state. Was the deploy completed?" >&2
  exit 1
fi

echo "Username: ${USERNAME}"
echo "Password: ${PASSWORD}"
