# ==============================================================================
# FILE: identity.tf — service identity for LiteLLM
# ------------------------------------------------------------------------------
# WHY A USER AND AN API KEY, WHEN OCI HAS INSTANCE PRINCIPALS
#
# Everything else this instance does — reading its own metadata, calling the
# Usage API, running the OCI CLI as the agent — goes through the instance
# principal granted in 03-openclaw/iam.tf. No key involved.
#
# The Gen AI call is the one exception, and it is LiteLLM's limitation rather
# than OCI's. LiteLLM's oci/ provider CAN authenticate with an instance
# principal, but only by being handed a live oci.signer object through the
# Python SDK. The proxy — which is what runs here, and what every other cloud
# in this series runs — is configured from YAML and environment variables, and
# those paths resolve manual credentials only: OCI_USER, OCI_FINGERPRINT,
# OCI_TENANCY, OCI_KEY, OCI_COMPARTMENT_ID, OCI_REGION.
#
# See litellm/llms/oci/common_utils.py: resolve_oci_credentials() reads exactly
# those six variables, and sign_oci_request() falls back to manual signing
# whenever no oci_signer object is present. A YAML config cannot supply one.
#
# So this is the honest tradeoff: a dedicated, single-purpose user whose ONLY
# grant is to call Gen AI. It cannot read storage, cannot touch compute, and
# cannot manage identity. The private key is generated by Terraform, never
# committed, and injected into the instance at boot as a 0600 environment file.
#
# NOT stored in OCI Vault, deliberately. See the note in oci-xubuntu-xrdp's
# vault.tf: OCI holds deleted vaults in PENDING_DELETION for a mandatory 30
# days while they still count against a default tenancy limit of one, so any
# destroy/rebuild loop wedges on LimitExceeded. This repo follows the same
# convention the other OCI projects settled on — secrets live in tfstate and
# reach the instance through templatefile.
#
# ALL RESOURCES HERE USE provider = oci.home. Tenancy-level IAM writes are
# rejected outside the home region with a 403 that never mentions regions.
# ==============================================================================

# ==============================================================================
# SECTION: Service User
# ==============================================================================

resource "oci_identity_user" "openclaw_svc" {
  provider       = oci.home
  compartment_id = var.tenancy_ocid
  name           = "openclaw-svc"
  description    = "OpenClaw LiteLLM proxy — Generative AI invocation and Email Delivery SMTP"

  # Required by Identity Domains — see var.svc_user_email. This user never
  # signs in and never receives mail; the address exists only to satisfy the
  # IDCS schema.
  email = var.svc_user_email
}

resource "oci_identity_group" "openclaw_svc" {
  provider       = oci.home
  compartment_id = var.tenancy_ocid
  name           = "openclaw-svc-group"
  description    = "Grants OpenClaw's LiteLLM proxy access to Generative AI"
}

resource "oci_identity_user_group_membership" "openclaw_svc" {
  provider = oci.home
  user_id  = oci_identity_user.openclaw_svc.id
  group_id = oci_identity_group.openclaw_svc.id
}

# ==============================================================================
# SECTION: API Signing Key
# ------------------------------------------------------------------------------
# OCI API signing keys must be RSA — an EC key is rejected at upload. OCI
# derives the fingerprint itself, so it is read back off the resource rather
# than computed here.
# ==============================================================================

resource "tls_private_key" "openclaw_svc" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "oci_identity_api_key" "openclaw_svc" {
  provider  = oci.home
  user_id   = oci_identity_user.openclaw_svc.id
  key_value = tls_private_key.openclaw_svc.public_key_pem
}

# ==============================================================================
# SECTION: Policy
# ------------------------------------------------------------------------------
# The entire grant. "use generative-ai-family" covers on-demand inference; it
# does not permit creating dedicated AI clusters, which is the expensive
# provisioned-capacity path this project deliberately avoids.
# ==============================================================================

resource "oci_identity_policy" "openclaw_genai" {
  provider       = oci.home
  compartment_id = var.compartment_ocid
  name           = "openclaw-genai-policy"
  description    = "Allows the OpenClaw service user to invoke Generative AI on demand"

  statements = [
    "Allow group ${oci_identity_group.openclaw_svc.name} to use generative-ai-family in compartment id ${var.compartment_ocid}",
  ]
}
